<!DOCTYPE html>
<html>
	<head>
	    <title><?php echo $this->user['display_name']; ?> &mdash; <?php echo SITE_NAME; ?></title>
	    <meta charset="UTF-8" />
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />	    
	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/html5shiv.js"></script>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/respond.min.js"></script>
		<![endif]-->	      	    
	    
	 	<?php
			if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ) {
	 			$currentTheme = ( strlen( @$_COOKIE['theme'] ) ) ? $_COOKIE['theme'] : SITE_DEFAULT_TEMPLATE;

	 			if( strlen( @$_COOKIE['themename'] ) ) {
	 				$themeDisplayName = $_COOKIE['themename'];
	 			}
	 			
			} else {
	 			$currentTheme = SITE_DEFAULT_TEMPLATE;
	 			setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
			}  
		?> 
		
		<?php $siteThemes		= $GLOBALS['SITE_THEMES']; ?>
		<?php $bootstrapThemes	= $GLOBALS['BOOTSTRAP_THEMES']; ?>    	 
				
		<?php if( !empty( $siteThemes ) ): ?>
			
			<?php 		
				if( $currentTheme != SITE_DEFAULT_TEMPLATE ) {
					if( !array_key_exists( $currentTheme, $siteThemes ) ) {
						$currentTheme = SITE_DEFAULT_TEMPLATE;
						setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
						
						if( isset( $themeDisplayName ) ) {
							unset( $themeDisplayName );
							setcookie( 'themename', '', time() - 3600, SITE_COOKIE_PATH );
						}
					}
				}
			?>
						
			<script type="text/javascript">	
				var BOOTSTRAP_THEMES	= new Array();	
				var SITE_THEMES			= new Array();
				
				<?php foreach( $siteThemes AS $key => $value ): ?>
					SITE_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';	
				<?php endforeach; ?>

				<?php foreach( $bootstrapThemes AS $key => $value ): ?>
					BOOTSTRAP_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';
				<?php endforeach; ?>				
			</script>
			<?php else: ?>
			<script type="text/javascript">		
				var BOOTSTRAP_THEMES	= new Array();
				var SITE_THEMES			= new Array();
			</script>			
		<?php endif; ?>
		
	    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
	    	<script type="text/javascript">
	    		var SITE_PHRASES = new Array();
				<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
					SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
				<?php endforeach; ?>
	    	</script>
	    <?php endif; ?>	
	    
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js?<?php echo rand(); ?>"></script>	    		   
		<script type="text/javascript">
			date_default_timezone_set('UTC');
			
			var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
			var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>';
			var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
			var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
			var SITE_NAME				= '<?php echo SITE_NAME; ?>';		
			var CURRENT_USER			= new Array();
			var UUID					= uuid();		
			var USE_BLOCKUI				= <?php echo (int)SITE_USE_BLOCKUI; ?>;
			var IS_MOBILE				= <?php echo (int)IS_MOBILE; ?>;
			var NEAR_BOTTOM_PX			= 100;
			var NEAR_BOTTOM				= false;
			var POST_APPEND_PROGRESS	= false;
			var ISSUE_ID				= parseInt( <?php echo $this->issue['id']; ?> );
			var INITIAL_XEDITABLE_REQ	= true;
					
			<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
				CURRENT_USER['<?php echo $key; ?>'] = '<?php echo base64_encode( $value ); ?>';
			<?php endforeach; ?>
		</script>     
	
	    <meta name="robots" content="noimageindex" />
	    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/favicon.ico" />
	        
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.8.3.min.js"></script>	
		
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/custom.css?<?php echo rand(); ?>" type="text/css" />				
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/font-awesome.min.css">
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/base/jquery-ui.css">
			    
	    <link id="bootstrapCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootstrap.min.css" rel="stylesheet"  media="screen">

		<?php if( $currentTheme != 'bootstrap-with-theme' ): ?>
	    	<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/bootstrap.min.css" rel="stylesheet">
	    <?php else: ?>
			<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/bootstrap/bootstrap.min.css" rel="stylesheet">    
	    <?php endif; ?>										     
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/homepage.css" type="text/css" />	
	    
	    <!-- Sticky Footer -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/sticky-footer-navbar.css" type="text/css" />		
	    
	    <!-- Bootstrap Switch -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/extensions/bootstrap-switch/bootstrap-switch.min.css" type="text/css" />								     
					
		<!-- JSviews -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jsrender.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observable.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jsviews.min.js"></script>
		<!-- JSviews -->
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><img src="<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>"></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->	
		<div id="fb-root"></div>
	    <script type="text/javascript">
	      window.fbAsyncInit = function() {
	        FB.init({
	          appId      : '<?php echo SITE_FACEBOOK_APP_ID; ?>',
	          xfbml      : true,
	          version    : 'v2.0'
	        });
	      };
	      (function(d, s, id){
	         var js, fjs = d.getElementsByTagName(s)[0];
	         if (d.getElementById(id)) {return;}
	         js = d.createElement(s); js.id = id;
	         js.src = "//connect.facebook.net/en_US/sdk.js";
	         fjs.parentNode.insertBefore(js, fjs);
	       }(document, 'script', 'facebook-jssdk'));
	    </script>		
		
	    <div class="navbar <?php if( @$_COOKIE['navbar-inverse'] == 1 ): ?> navbar-inverse <?php else: ?> navbar-default <?php endif; ?> navbar-fixed-top">
			<div class="container-fluid">
	        	<div class="navbar-header">
					<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>" class="blockUI-trigger navbar-brand" alt="<?php echo SITE_NAME; ?>" title="<?php echo SITE_NAME; ?>"><i class="fa fa-life-ring"></i></a>
	          		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	          		</button>
	        	</div>
	        	<div class="navbar-collapse collapse" id="navbar-main">
	          		<ul class="nav navbar-nav">
	          			<!-- START:	Dashboards -->
	          			<li class="dropdown">
	          				<a id="dropdownDashboards" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('dashboards');?></a>
			              	<ul aria-labelledby="dropdownDashboards" class="dropdown-menu">
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>">
										<?php echo translate( 'system_dashboard' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Dashboards -->
	          			
	          			<?php FB::info( $_SESSION ); ?>

	          			<!-- START:	Projects -->
	          			<li class="dropdown">
	          				<a id="dropdownProjects" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('projects');?></a>
			              	<ul aria-labelledby="dropdownProjects" class="dropdown-menu">
          						<li class="dropdown-header"><?php echo translate('current_project'); ?></li>				              		
			              		<li>
			              			<a href="<?php echo PROTOCOL_RELATIVE_URL.'/project/'.$this->issue['metadata']['project']['key']; ?>">
			              				<?php echo $this->issue['metadata']['project']['branding']; ?> <?php echo $this->issue['metadata']['project']['title']; ?> (<?php echo $this->issue['metadata']['project']['key']; ?>)
			              			</a>
			              		</li>
          						<li class="divider"></li>			              	
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/projects">
										<?php echo translate( 'view_all_projects' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Projects -->

	          			<!-- START:	Issues -->
	          			<li class="dropdown">
	          				<a id="dropdownIssues" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('issues');?></a>
			              	<ul aria-labelledby="dropdownIssue" class="dropdown-menu">
          						<li class="dropdown-header"><?php echo translate('current_project'); ?></li>				              		
			              		<li>
			              			<a href="<?php echo PROTOCOL_RELATIVE_URL.'/project/'.$this->issue['metadata']['project']['key']; ?>/#issues">
			              				<?php echo $this->issue['metadata']['project']['branding']; ?> <?php echo $this->issue['metadata']['project']['title']; ?> (<?php echo $this->issue['metadata']['project']['key']; ?>)
			              			</a>
			              		</li>
          						<li class="divider"></li>		              		
								<?php if( has_permission( 'can_create_issues' ) ): ?>
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/issue/create">
										<?php echo translate( 'create_issue' ); ?>
									</a>
			              		</li>			              	
			              		<?php endif; ?>
								<li>
									<a href="#">
										<?php echo translate( 'search_issues' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Issues -->
	          		
			            <?php if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ): ?>        
			            <li class="dropdown">
			              <a id="themes" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('themes');?> (<?php echo count( $GLOBALS['SITE_THEMES'] ); ?>)</a>
			              <ul aria-labelledby="themes" class="dropdown-menu" id="dropdownThemes">
							<li>								
								<a id="linkThemeCurrent" href="#" class="changeTheme" data-displayname="" data-name="<?php echo strtolower( $currentTheme ); ?>">
									<?php echo ( isset( $themeDisplayName ) ) ? $themeDisplayName : ucfirst( $currentTheme ); ?>
								</a>
			              	</li>
			              	<li>
			              		<a href="#"><div><input data-size="normal" class="bootstrap-switch" type="checkbox" id="navbarInverse" name="navbarInverse" value="1" <?php if( @$_COOKIE['navbar-inverse'] == 1 ): ?> checked="checked"<?php endif; ?>></div></a>
			              	</li>			              	
			              	<li class="divider"></li>
			              	<?php foreach( $GLOBALS['SITE_THEMES'] AS $key => $value ): ?>
		                		<li <?php if( strtolower( $key ) == strtolower( $currentTheme ) ): ?> class="active" <?php endif; ?>>
		                			<?php if( array_key_exists( $key, $GLOBALS['BOOTSTRAP_THEMES'] ) ): 
		                				$isBootstrap = true;
		                			else:
		                				$isBootstrap = false;
		                			endif; 
		                			?>
		                			<a <?php if( strtolower( $key ) == strtolower( $currentTheme ) ): ?> style="font-weight: bold;" <?php endif; ?> href="#" class="changeTheme <?php echo strtolower( $key ); ?>" data-bootstrap="<?php echo $isBootstrap; ?>" data-displayname="<?php echo $value; ?>" data-name="<?php echo strtolower( $key ); ?>">
		                				<?php echo $value; ?>
									</a>                			
								</li>
			              	<?php endforeach; ?>
			              </ul>
			            </li>
			            <?php endif; ?>
			            			            			            
			            <?php if( (int)SITE_ALLOW_LANGUAGE_CHANGE == 1 ): ?> 
			            	<?php if( !empty( $GLOBALS['SITE_LANGUAGES'] ) ): ?>			            	       
			            		<li class="dropdown">
					              <a id="changeLang" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('language'); ?></a>
					              <ul aria-labelledby="changeLang" class="dropdown-menu">
									<li>
										<a id="linkLanguageCurrent" href="#" class="changeLang" data-name="<?php echo strtolower( $currentTheme ); ?>">
											<?php $CloneUI_Language = new CloneUI_Language; ?>
											<?php echo $CloneUI_Language->fetchFriendlyNameById( $_SESSION['user']['site_language'] ); ?>
										</a>
					              	</li>
				                		<li class="divider"></li>
						              	<?php foreach( $GLOBALS['SITE_LANGUAGES'] AS $key => $value ): ?>
					                		<li>
					                			<?php if( $value['id'] != $_SESSION['user']['site_language'] ): ?>
						                			<a href="#" class="changeLang" id="changeLang-<?php echo $value['id']; ?>" data-id="<?php echo $value['id']; ?>" data-name="<?php echo $value['iso_3166_1']; ?>">
						                				<?php echo $value['friendly_name']; ?>
													</a>
												<?php else: ?>
													<a class="noBlockUI">
														<?php echo $value['friendly_name']; ?>
													</a>																										
												<?php endif; ?>               			
											</li>              	
						              	<?php endforeach; ?>
			              			</ul>
			            		</li>
			            	<?php endif; ?>			            		
			            <?php endif; ?>			             		             
	          		</ul>

					<!-- START:	Search Form -->
					<form action="<?php echo PROTOCOL_RELATIVE_URL; ?>/search" method="GET" name="frmSiteSearch" id="frmSiteSearch" class="navbar-form navbar-left">
	                	<input name="q" id="frmSearchQuery" type="text" placeholder="<?php echo translate('search'); ?>" class="form-control col-lg-8">
	                </form>
					<!-- END:	Search Form -->
	
	          		<ul class="nav navbar-nav navbar-right">	          		
	            		<li class="dropdown">
	              			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-help"> <i class="fa fa-question-circle"></i></a>
	              			<ul class="dropdown-menu" aria-labelledby="dropdown-help">
		            			<li>
		            				<a id="aboutJordon" href="#"><?php echo translate('about'); ?> Jordon</a>
		            			</li>
	              			</ul>
	            		</li>
	          			<?php if( (int)$_SESSION['user']['logged_in'] == 1 ): ?>
	            		<li class="dropdown">
	              			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-user"><?php if( isset( $_SESSION['user']['external']['network'] ) ):?> <i class="fa fa-<?php echo $_SESSION['user']['external']['network']; ?>"></i> <?php endif;?><?php echo $_SESSION['user']['email']; ?></a>
	              			<ul class="dropdown-menu" aria-labelledby="dropdown-user">
		            			<li>
		            				<a id="linkLogout" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/logout"><i class="fa fa-user"></i> <?php echo translate('logout'); ?></a>
		            			</li>
	              			</ul>
	            		</li>	
	            		<?php else: ?>       
            			<li>
            				<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/login"><i class="fa fa-user"></i> <?php echo translate('login'); ?></a>
            			</li>	            		
	            		<?php endif; ?>   		
	          		</ul>
	        	</div>
			</div>
		</div>
	
	
		<!-- START:		Main Container -->
	    <div class="container-fluid">	
	    	<div class="row" style="margin-left: 10px;">  		
    			<table <?php if( canAdmin() ): ?> class="adminActionTrigger" <?php endif;?> style="width: 100%; border-spacing: 0px; border-collapse: separate;">
    				<tbody>
    					<tr class="adminAction">
    						<td colspan="2" style="align: right; text-align: right;">
    							<?php if( has_permission( 'can_delete_users' ) ): ?>
    								<i data-id="<?php echo $this->user['id']; ?>" alt="<?php echo translate('edit'); ?>" title="<?php echo translate('edit'); ?>" class="issueEdit fa fa-pencil"></i>&nbsp;
    							<?php endif; ?>
    						    <?php if( has_permission( 'can_edit_users' ) ): ?>
    								<i data-projectkey="<?php echo $this->issue['metadata']['project']['key']; ?>" data-uuid="<?php echo $this->issue['uuid']; ?>" data-projectid="<?php echo $this->issue['project_id']; ?>" data-id="<?php echo $this->issue['id']; ?>" alt="<?php echo translate('delete'); ?>" title="<?php echo translate('delete'); ?>" class="issueDelete fa fa-times-circle"></i>&nbsp;
    							<?php endif; ?>    							 
    						</td>     					
    					</tr>
    					<tr>
    						<td style="width: 2%; vertical-align: middle;">
    							<img src="<?php echo $this->user['avatar_url']; ?>" border="0" class="profileThumb thumbnail img-responsive">
    						</td>
    						<td style="vertical-align: top; padding-left: 10px;">
    							<h1 style="margin-top: 0; margin-bottom: 0;"><?php echo $this->user['display_name']; ?></h1>
    						</td>						
    					</tr>
    				</tbody>
    			</table>	    		
	    	</div>
	    	<hr>
	    	<div class="row">
				<div class="col-lg-12">
			    	<div class="col-lg-6">
			    		<fieldset>
    						<legend><?php echo translate('details'); ?></legend>
				    		<div style="margin-top: 10px; margin-bottom: 10px;">
				    			<table style="width: 100%;">
				    				<tr>
				    					<td>			    					
				    						<?php echo translate('full_name'); ?>
				    					</td>
				    					<td>			    					
				    						<?php echo $this->user['first_name'].' '.$this->user['last_name']; ?>
				    					</td>	    								    					
				    				</tr>
				    				<?php if( has_permission('email_can_view') ): ?>				    			
				    				<tr>
				    					<td>			    					
				    						<?php echo translate('email'); ?>
				    					</td>
				    					<td>			    					
				    						<?php echo $this->user['email']; ?>
				    					</td>	    								    					
				    				</tr>
				    				<?php endif; ?>				    			
				    				<tr>
				    					<td>			    					
				    						<?php echo translate('last_seen'); ?>
				    					</td>
				    					<td>			    					
				    						<?php echo date( SITE_DATE_FORMAT, $this->user['last_active'] ); ?>
				    					</td>	    								    					
				    				</tr>
				    				<tr>
				    					<td>
				    						<?php echo translate('last_login_date'); ?>
				    					</td>
				    					<td>
											<?php echo date( SITE_DATE_FORMAT, $this->user['last_login_date'] ); ?>
				    					</td>			    								    					
				    				</tr>
				    				<tr>
				    					<td>
				    						<?php echo translate('join_date'); ?>
				    					</td>
				    					<td>
			    							<?php echo date( SITE_DATE_FORMAT, $this->user['date_created'] ); ?>
				    					</td>			    								    					
				    				</tr>				    								    							    				
				    			</table>
				    		</div>    						
  						</fieldset>			    	

						<!-- START:	Description -->
			    		<fieldset style="margin-top: 20px;">
    						<legend><?php echo translate('assigned_issues'); ?></legend>
				    		<div data-name="description" class="xeditable issueData" data-type="textarea" data-pk="<?php echo $this->issue['id']; ?>" data-title="<?php echo translate('issue_description'); ?>" style="margin-bottom: 10px;"><?php echo nl2br( $this->issue['description'] ); ?></div>
			    		</fieldset>
						<!-- END:	Description -->

			        </div>
			
			        <div class="col-lg-6">
			    		<fieldset>
    						<legend><?php echo translate('activity'); ?></legend>
				    		<div style="margin-top: 10px; margin-bottom: 10px;">
				    			<table style="width: 100%;">
				    				<tr>
										<td></td>		    								    					
				    				</tr>		    				
				    			</table>
				    		</div>
				    	</fieldset>
				    </div>			    				
			 	</div>    	
	    	</div>
	    </div>
	    <!-- END:	Main Container -->
	    
	    
		<div class="footer">
			<div class="container-fluid">
		    	<div class="row">
		        	<div class="col-lg-12">		
		            	<ul class="list-unstyled">
		              		<li class="pull-right">
		              			<a href="#top" class="backToTop noBlockUI">
		              				<i class="fa fa-chevron-up"></i>
		              			</a>&nbsp;
								<a href="#top" class="backToTop noBlockUI">	              	
									<?php echo translate('to_top'); ?>
		              			</a>
		              		</li>
		              		<li>
		              			<i class="fa fa-rss-square"></i>&nbsp;<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/rss">RSS</a>
		              		</li>
		            	</ul>
		            	<p>&copy; <?php echo translate('copyright'); ?> <?php echo date('Y'); ?> <?php echo SITE_NAME; ?>. <?php echo translate('all_rights_reserved'); ?>.</p>		
		          	</div>
		        </div>
      		</div>
    	</div>
    	    
		<script type="text/javascript">
		    $(document).ready(function() {	
				// Bootstrap Switch
		    	$('.bootstrap-switch').bootstrapSwitch({
			    	'size': 'mini',
			    	'onText': 'Inverse',
			    	'offText': 'Normal',
			    	'onSwitchChange': function(event, state) {
				    	$.blockUI();
				    	
						if( state ) {
							$.cookie('navbar-inverse', 1, { 
								expires: 7300, 
								path: '/',
								onSet: function( value ) {
									window.location.reload();
								}	 
							});
							$('div.navbar').addClass('navbar-inverse');
						} else {
							$('div.navbar').removeClass('navbar-inverse');
							$.removeCookie('navbar-inverse', { 
								path: '/',
								onSet: function( value ) {
									window.location.reload();
								} 
							});
						}	
					 },
					 'onInit': function( event, state ) {
						$('#dropdownThemes').css({
							 'width': ( $('#dropdownThemes').width() + $('#navbarInverse').width() ) + 'px' 
						});

						if( $.cookie('navbar-inverse') == 1 ) {
							$('div.navbar').addClass('navbar-inverse');
						} else {
							$('div.navbar').removeClass('navbar-inverse');
						}						 
					 }		 
			    });
		    			    				    							    		    		   			     			   
				$.imgpreload([
					DEFAULT_PRELOADER_IMAGE, 
					BASEURL + '/images/preloader/168.gif'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});	

				// JSViews
				$.templates({
					templateComments: '#templateComments'
				});

			  	$('[data-toggle="tabAjax"]').click(function(event) {
			  	    var ME = $(this);
	
				     // activated tab
			  	    var currentTab = event.target 
	
			  	    // part
			  	    var part = ME.data('part');
	
			  	    if( typeof part === 'undefined' ) {
			  	    	return false;
				  	}    
	
			  	    // get the target element
			  	    var targetId		= $(currentTab).attr('href').substr(1);
				  	var targetElement	= $('#' + targetId);
	
					$.ajax({
						type: 'POST',
						url: BASEURL + '/issue/ajax',
						data: { 
							method: 'info',
							part: part,
							id: <?php echo (int)$this->issue['id']; ?>
						},
						complete: function( jqXHR, textStatus ) {
							// ..
						},
						success: function( response, textStatus, jqXHRresponse ) {
							if( response.status == 'OK' ) {
								var data = response.data;
	
								if( data.length > 0 ) {
									// iterate
									$.each(data, function( index, value ) {
										data[index]['date_created']		= date( 'l, F m, Y / h:i:s A e', value.date_created );
										data[index]['priority_name'] 	= translate( value.priority_name );
										data[index]['status_name'] 		= translate( value.status_name );
										data[index]['project_key']		= '<?php echo $this->project['key']; ?>';
									});
									
									// add messages to the DOM
									targetElement.html(
										$.render.templateComments( response.data )
									);								
								} else {
									targetElement.html( '<div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i> '+ translate('no_data') +'</div>' );
								}					
							} else {
								if( response.status == 'ERROR' ) {
									targetElement.html( '<div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i> '+ response.error +'</div>' );	
								}	
							}
	
							// show the tab
							ME.tab('show');
						},
						error: function(  jqXHR, textStatus, errorThrown ) {
							// ...
						},		
						dataType: 'json'
					});	
			  	    
			  	    return false;
			  	});		 	
			    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});															    
		    });	   	    		    				    
		</script>	
				
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootstrap.min.js"></script>
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootswatch.js"></script>		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jstorage.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/imagesloaded.pkgd.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.defaults.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observor.js?<?php echo rand(); ?>"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/custom.js?<?php echo rand(); ?>"></script>				
				
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootstrap-switch/bootstrap-switch.min.js"></script>			
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>	
		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.autosize.min.js"></script>		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/issue.js"></script>
		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/moment/moment.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/livestamp.min.js"></script> 
		
		<!-- replaceText -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.ba-replacetext.min.js"></script>
		
		<!-- SmartMenus -->
		<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/smartmenus/jquery.smartmenus.bootstrap.css" rel="stylesheet">
		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>
		
		<!-- Q -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/q.min.js"></script>
				
		<script id="templateComments" type="text/x-jsrender">
			<div id="comment-{{>id}}">
				<table class="commentTable <?php if( canAdmin() ): ?>adminActionTrigger<?php endif; ?>" style="border-spacing: 5px; border-collapse: separate; margin-bottom: 10px; width: 100%;">
					<tbody>
						<?php if( has_permission('can_delete_issue_comments') ): ?>
						<tr class="adminAction">
							<td style="align: right; text-align: right;" colspan="2">
								<i data-id="{{>id}}" alt="<?php echo translate('delete'); ?>" title="<?php echo translate('delete'); ?>" class="deleteComment fa fa-times-circle"></i>
							</td>
						</tr>
						<?php endif; ?>
						<tr>
							<td>
							<?php if ( (int)@$_SESSION['user']['id'] < 1 ): ?>
								<?php echo translate('guest'); ?>
							<?php else: ?>
								<a target="_blank" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/profile/<?php echo $_SESSION['user']['url_slug']; ?>"><?php echo $_SESSION['user']['display_name']; ?></a>
							<?php endif; ?>
							</td>
							<td style="align: right; text-align: right;">
								<span alt="{{>dateFull}}" title="{{>dateFull}}" data-livestamp="{{>date}}"></span>&nbsp;&nbsp;<a class="noBlockUI" target="_self" href="<?php echo BASEURL; ?>/issue/<?php echo $this->issue['metadata']['project']['key'].'-'.$this->issue['id']; ?>#comment-{{>id}}"><i class="fa fa-link"></i></a>
							</td>
						</tr>
						<tr>
							<td colspan="2" class="commentText" id="commentText-{{>id}}">
							{{:comment}}
							</td>
						</tr>
					</tbody>
				</table>
				<hr>
			</div>
		</script>  
		
		<!-- Select2 -->
		<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/select2/select2.css" rel="stylesheet" type="text/css"></link>  
		<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/select2-bootstrap.css" rel="stylesheet" type="text/css"></link>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/select2/select2.js"></script>  
					
		<?php if( has_permission( 'can_edit_issues' ) ): ?>		
			<!-- x-editable -->
			<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap-editable.css" rel="stylesheet"/>
			<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/x-editable/bootstrap-editable.min.js"></script>
			
			<style type="text/css">
				.editableform-loading {
				    width: 100% !important; 
				}
	
				.editableform {
					margin-top: 5px;	
				}
			</style> 
		<?php endif; ?>
	</body>	
</html>