<!DOCTYPE html>
<html>
	<head>
	    <title><?php echo $this->project['title']; ?> &mdash; <?php echo SITE_NAME; ?></title>
	    <meta charset="UTF-8" />
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />	    
	    	    
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootswatch.min.css">
	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/html5shiv.js"></script>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/respond.min.js"></script>
		<![endif]-->	      	    
	    
	 	<?php
			if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ) {
	 			$currentTheme = ( strlen( @$_COOKIE['theme'] ) ) ? $_COOKIE['theme'] : SITE_DEFAULT_TEMPLATE;

	 			if( strlen( @$_COOKIE['themename'] ) ) {
	 				$themeDisplayName = $_COOKIE['themename'];
	 			}
	 			
			} else {
	 			$currentTheme = SITE_DEFAULT_TEMPLATE;
	 			setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
			}
		?> 
		
		<?php $siteThemes		= $GLOBALS['SITE_THEMES']; ?>
		<?php $bootstrapThemes	= $GLOBALS['BOOTSTRAP_THEMES']; ?>    	 
				
		<?php if( !empty( $siteThemes ) ): ?>
			
			<?php 		
				if( $currentTheme != SITE_DEFAULT_TEMPLATE ) {
					if( !array_key_exists( $currentTheme, $siteThemes ) ) {
						$currentTheme = SITE_DEFAULT_TEMPLATE;
						setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
						
						if( isset( $themeDisplayName ) ) {
							unset( $themeDisplayName );
							setcookie( 'themename', '', time() - 3600, SITE_COOKIE_PATH );
						}
					}
				}
			?>
						
			<script type="text/javascript">	
				var BOOTSTRAP_THEMES	= new Array();	
				var SITE_THEMES			= new Array();
				
				<?php foreach( $siteThemes AS $key => $value ): ?>
					SITE_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';	
				<?php endforeach; ?>

				<?php foreach( $bootstrapThemes AS $key => $value ): ?>
					BOOTSTRAP_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';
				<?php endforeach; ?>				
			</script>
			<?php else: ?>
			<script type="text/javascript">		
				var BOOTSTRAP_THEMES	= new Array();
				var SITE_THEMES			= new Array();
			</script>			
		<?php endif; ?>
		
	    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
	    	<script type="text/javascript">
	    		var SITE_PHRASES = new Array();
				<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
					SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
				<?php endforeach; ?>
	    	</script>
	    <?php endif; ?>	
	    
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js?<?php echo rand(); ?>"></script>	    		   
		<script type="text/javascript">
			date_default_timezone_set('UTC');
			
			var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
			var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>';
			var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
			var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
			var SITE_NAME				= '<?php echo SITE_NAME; ?>';		
			var CURRENT_USER			= new Array();
			var UUID					= uuid();		
			var USE_BLOCKUI				= <?php echo (int)SITE_USE_BLOCKUI; ?>;
			var IS_MOBILE				= <?php echo (int)IS_MOBILE; ?>;	
					
			<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
				CURRENT_USER['<?php echo $key; ?>'] = '<?php echo base64_encode( $value ); ?>';
			<?php endforeach; ?>
		</script>     
	
	    <meta name="robots" content="noimageindex" />
	    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/favicon.ico" />
	        
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.8.3.min.js"></script>	
		
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/custom.css?<?php echo rand(); ?>" type="text/css" />				
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/font-awesome.min.css">
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/base/jquery-ui.css">
			    
	    <link id="bootstrapCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootstrap.min.css" rel="stylesheet"  media="screen">

		<?php if( $currentTheme != 'bootstrap-with-theme' ): ?>
	    	<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/bootstrap.min.css" rel="stylesheet">
	    <?php else: ?>
			<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/bootstrap/bootstrap.min.css" rel="stylesheet">    
	    <?php endif; ?>										     
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/homepage.css" type="text/css" />	
	    
	    <!-- Sticky Footer -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/sticky-footer-navbar.css" type="text/css" />	
	    
	    <!-- Desktop Sidebar Left -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/desktop-sidebar-left.css" type="text/css" />		
	    
	    <!-- Bootstrap Switch -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/extensions/bootstrap-switch/bootstrap-switch.min.css" type="text/css" />	
	    
	    <!-- Bootstrap Vertical Tabs -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/extensions/bootstrap.vertical-tabs/bootstrap.vertical-tabs.min.css" type="text/css" />								     
					
		<!-- JSviews -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jsrender.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observable.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jsviews.min.js"></script>
		<!-- JSviews -->
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><img src="<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>"></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->	
		<div id="fb-root"></div>
	    <script type="text/javascript">
	      window.fbAsyncInit = function() {
	        FB.init({
	          appId      : '<?php echo SITE_FACEBOOK_APP_ID; ?>',
	          xfbml      : true,
	          version    : 'v2.0'
	        });
	      };
	      (function(d, s, id){
	         var js, fjs = d.getElementsByTagName(s)[0];
	         if (d.getElementById(id)) {return;}
	         js = d.createElement(s); js.id = id;
	         js.src = "//connect.facebook.net/en_US/sdk.js";
	         fjs.parentNode.insertBefore(js, fjs);
	       }(document, 'script', 'facebook-jssdk'));
	    </script>		
		
	    <div class="navbar <?php if( @$_COOKIE['navbar-inverse'] == 1 ): ?> navbar-inverse <?php else: ?> navbar-default <?php endif; ?> navbar-fixed-top">
			<div class="container-fluid">
	        	<div class="navbar-header">
					<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>" class="blockUI-trigger navbar-brand" alt="<?php echo SITE_NAME; ?>" title="<?php echo SITE_NAME; ?>"><i class="fa fa-life-ring"></i></a>
	          		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	          		</button>
	        	</div>
	        	<div class="navbar-collapse collapse" id="navbar-main">
	          		<ul class="nav navbar-nav">
	          			<!-- START:	Dashboards -->
	          			<li class="dropdown">
	          				<a id="dropdownDashboards" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('dashboards');?></a>
			              	<ul aria-labelledby="dropdownDashboards" class="dropdown-menu">
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>">
										<?php echo translate( 'system_dashboard' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Dashboards -->

	          			<!-- START:	Projects -->
	          			<li class="dropdown">
	          				<a id="dropdownProjects" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('projects');?></a>
			              	<ul aria-labelledby="dropdownProjects" class="dropdown-menu">
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/projects">
										<?php echo translate( 'view_all_projects' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Projects -->

	          			<!-- START:	Issues -->
	          			<li class="dropdown">
	          				<a id="dropdownIssues" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('issues');?></a>
			              	<ul aria-labelledby="dropdownIssue" class="dropdown-menu">
								<?php if( has_permission( 'can_create_issues' ) ): ?>
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/issue/create">
										<?php echo translate( 'create_issue' ); ?>
									</a>
			              		</li>			              	
			              		<?php endif; ?>			              	
								<li>
									<a href="#">
										<?php echo translate( 'search_issues' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Issues -->
	          		
			            <?php if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ): ?>        
			            <li class="dropdown">
			              <a id="themes" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('themes');?> (<?php echo count( $GLOBALS['SITE_THEMES'] ); ?>)</a>
			              <ul aria-labelledby="themes" class="dropdown-menu" id="dropdownThemes">
							<li>								
								<a id="linkThemeCurrent" href="#" class="changeTheme" data-displayname="" data-name="<?php echo strtolower( $currentTheme ); ?>">
									<?php echo ( isset( $themeDisplayName ) ) ? $themeDisplayName : ucfirst( $currentTheme ); ?>
								</a>
			              	</li>
			              	<li>
			              		<a href="#"><div><input data-size="normal" class="bootstrap-switch" type="checkbox" id="navbarInverse" name="navbarInverse" value="1" <?php if( @$_COOKIE['navbar-inverse'] == 1 ): ?> checked="checked"<?php endif; ?>></div></a>
			              	</li>			              	
			              	<li class="divider"></li>
			              	<?php foreach( $GLOBALS['SITE_THEMES'] AS $key => $value ): ?>
		                		<li <?php if( strtolower( $key ) == strtolower( $currentTheme ) ): ?> class="active" <?php endif; ?>>
		                			<?php if( array_key_exists( $key, $GLOBALS['BOOTSTRAP_THEMES'] ) ): 
		                				$isBootstrap = true;
		                			else:
		                				$isBootstrap = false;
		                			endif; 
		                			?>
		                			<a <?php if( strtolower( $key ) == strtolower( $currentTheme ) ): ?> style="font-weight: bold;" <?php endif; ?> href="#" class="changeTheme <?php echo strtolower( $key ); ?>" data-bootstrap="<?php echo $isBootstrap; ?>" data-displayname="<?php echo $value; ?>" data-name="<?php echo strtolower( $key ); ?>">
		                				<?php echo $value; ?>
									</a>                			
								</li>
			              	<?php endforeach; ?>
			              </ul>
			            </li>
			            <?php endif; ?>
			            			            			            
			            <?php if( (int)SITE_ALLOW_LANGUAGE_CHANGE == 1 ): ?> 
			            	<?php if( !empty( $GLOBALS['SITE_LANGUAGES'] ) ): ?>			            	       
			            		<li class="dropdown">
					              <a id="changeLang" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('language'); ?></a>
					              <ul aria-labelledby="changeLang" class="dropdown-menu">
									<li>
										<a id="linkLanguageCurrent" href="#" class="changeLang" data-name="<?php echo strtolower( $currentTheme ); ?>">
											<?php $CloneUI_Language = new CloneUI_Language; ?>
											<?php echo $CloneUI_Language->fetchFriendlyNameById( $_SESSION['user']['site_language'] ); ?>
										</a>
					              	</li>
				                		<li class="divider"></li>
						              	<?php foreach( $GLOBALS['SITE_LANGUAGES'] AS $key => $value ): ?>
					                		<li>
					                			<?php if( $value['id'] != $_SESSION['user']['site_language'] ): ?>
						                			<a href="#" class="changeLang" id="changeLang-<?php echo $value['id']; ?>" data-id="<?php echo $value['id']; ?>" data-name="<?php echo $value['iso_3166_1']; ?>">
						                				<?php echo $value['friendly_name']; ?>
													</a>
												<?php else: ?>
													<a class="noBlockUI">
														<?php echo $value['friendly_name']; ?>
													</a>																										
												<?php endif; ?>               			
											</li>              	
						              	<?php endforeach; ?>
			              			</ul>
			            		</li>
			            	<?php endif; ?>			            		
			            <?php endif; ?>			             		             
	          		</ul>

					<!-- START:	Search Form -->
					<form action="<?php echo PROTOCOL_RELATIVE_URL; ?>/search" method="GET" name="frmSiteSearch" id="frmSiteSearch" class="navbar-form navbar-left">
	                	<input name="q" id="frmSearchQuery" type="text" placeholder="<?php echo translate('search'); ?>" class="form-control col-lg-8">
	                </form>
					<!-- END:	Search Form -->
	
	          		<ul class="nav navbar-nav navbar-right">
	            		<li class="dropdown">
	              			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-help"> <i class="fa fa-question-circle"></i></a>
	              			<ul class="dropdown-menu" aria-labelledby="dropdown-help">
		            			<li>
		            				<a id="aboutJordon" href="#"><?php echo translate('about'); ?> Jordon</a>
		            			</li>
	              			</ul>
	            		</li>
	          			<?php if( (int)$_SESSION['user']['logged_in'] == 1 ): ?>
	            		<li class="dropdown">
	              			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-user"><?php if( isset( $_SESSION['user']['external']['network'] ) ):?> <i class="fa fa-<?php echo $_SESSION['user']['external']['network']; ?>"></i> <?php endif;?><?php echo $_SESSION['user']['email']; ?></a>
	              			<ul class="dropdown-menu" aria-labelledby="dropdown-user">
		            			<li>
		            				<a id="linkLogout" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/logout"><?php echo translate('logout'); ?></a>
		            			</li>
	              			</ul>
	            		</li>	
	            		<?php else: ?>       
            			<li>
            				<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/login"><?php echo translate('login'); ?></a>
            			</li>	            		
	            		<?php endif; ?>   		
	          		</ul>
	        	</div>
			</div>
		</div>
	
	
		<!-- START:		Main Container -->
	    <div class="container-fluid">	
	    	<div class="row" style="margin-left: 10px;">
	    		<div> 
	    			<h1><?php echo $this->project['branding']; ?> <?php echo $this->project['title']; ?></h1>   		
	    			<table style="width: 100%; border-spacing: 0px; border-collapse: separate;">
	    				<tbody>
	    					<tr>
	    						<td style="padding: 20px;">
	    						<?php echo translate('key'); ?>:&nbsp;&nbsp;<?php echo $this->project['key']; ?>
	    						</td>
	    						<td style="padding: 20px;">
	    						<?php echo translate('lead'); ?>:&nbsp;&nbsp;<a href="<?php echo PROTOCOL_RELATIVE_URL.'/profile/'.$this->project['metadata']['lead_info']['url_slug']; ?>"><?php echo $this->project['metadata']['lead_info']['first_name'].' '.$this->project['metadata']['lead_info']['last_name']; ?></a>
	    						</td>
	    						<td style="padding: 20px;">
	    						<?php $categoryId	= ( isset( $this->project['metadata']['category'][0]['id'] ) ) ? $this->project['metadata']['category'][0]['id'] : 0; ?>
	    						<?php $categoryName = ( isset( $this->project['metadata']['category'][0]['title'] ) ) ? $this->project['metadata']['category'][0]['title'] : translate('uncategorized'); ?>
	    						<?php echo translate('category'); ?>:&nbsp;&nbsp;<a href="<?php echo PROTOCOL_RELATIVE_URL.'/projects/'.$categoryId; ?>"><?php echo $categoryName; ?></a>
	    						</td>	
	    						<td style="padding: 20px;">
	    						URL:&nbsp;&nbsp;<a href="<?php echo $this->project['url']; ?>" target="_blank"><?php echo $this->project['url']; ?></a>
	    						</td>    						
	    					</tr>
	    				</tbody>
	    			</table>
	    		</div>	    		
	    	</div>
	    	<hr>
	    	<div class="row">
				<div class="col-lg-12">
			    	<div class="col-lg-2"> <!-- required for floating -->
			        	<!-- Nav tabs -->
			          	<ul class="nav nav-tabs tabs-left">
			            	<li class="active">
			            		<a id="triggerSummary" href="#summary" data-toggle="tab" data-part="summary"><?php echo translate('summary'); ?></a>
			            	</li>
			            	<li>
			            		<a id="triggerIssues" href="#issues" data-toggle="tabAjax" data-part="issues"><?php echo translate('issues'); ?></a>
			            	</li>
			          	</ul>
			        </div>
			
			        <div class="col-lg-10" id="allTabs">
			        	<!-- Tab panes -->
			          	<div class="tab-content">
			            	<div class="tab-pane active" id="summary">
								<div class="<?php if( has_permission( 'project_can_view_activity_stream' ) ): ?>col-lg-5<?php endif;?>">
						        	<h3><?php echo translate('summary'); ?></h3>
						        	<hr>
						        	<?php if( strlen( trim( $this->project['description'] ) ) ): ?>
    						        	<?php echo nl2br( $this->project['description'] ); ?>						        	
    						        	<hr>
						        	<?php endif; ?>
						        	
									<div id="issueChart">
										<?php echo SITE_LOADING_PLACEHOLDER_SMALL; ?>
									</div>
        						</div>		
        						<?php if( has_permission( 'project_can_view_activity_stream' ) ): ?>	            	
									<div class="col-lg-5">
							        	<h3><?php echo translate('activity_stream'); ?></h3>
							        	<hr>
							        	<?php if( empty( $this->activity ) ): ?>
							        	<div class="alert alert-info" role="alert">
							        		<i class="fa fa-exclamation-triangle"></i> <?php echo translate('no_recent_activity'); ?>
							        	</div>
							        	<?php else: ?>
							        	<div id="activityStream">
							        		<?php echo SITE_LOADING_PLACEHOLDER_SMALL; ?>
							        	</div>
							        	<?php endif; ?>
	        						</div>	
        						<?php endif; ?>		            	
			            	</div>
			            	<div class="tab-pane" id="issues">
								<!-- div class="row">
									<div class="col-lg-12">
										<h2 style="margin-bottom: 20px;"><?php echo translate('issues'); ?></h2>
										<div class="col-lg-4">
											<?php echo translate('all_issues'); ?>
											<br>
											<?php echo translate('unresolved'); ?>
										</div>
										<div class="col-lg-4">
											<?php echo translate('added_recently'); ?>
											<br>
											<?php echo translate('resolved_recently'); ?>
											<br>
											<?php echo translate('updated_recently'); ?>
										</div>
										<div class="col-lg-4">
											<?php echo translate('unscheduled'); ?>
											<br>
											<?php echo translate('outstanding'); ?>
										</div>
									</div>
								</div>
								<hr -->
								
								<div class="row" style="margin-top: 20px;">
									<div class="col-lg-6">
										<h2 style="margin-bottom: 20px;"><?php echo translate('recent'); ?></h2>
										<table id="tblRecentIssues" style="width: 100%; border-spacing: 0px; border-collapse: separate;">
					  						<thead>
					    						<tr>
					      							<th><?php echo translate('title'); ?></th>
													<th><?php echo translate('status'); ?></th>
													<th><?php echo translate('priority'); ?></th>
													<th><?php echo translate('date_created'); ?></th>
					      							<th><?php echo translate('last_updated'); ?></th>
					    						</tr>
					  						</thead>
											<tbody id="recentIssueList"></tbody>
										</table>
									</div>
								
									<div class="col-lg-6">
										<h2 style="margin-bottom: 20px;"><?php echo translate('summary'); ?></h2>
										<table style="width: 100%; border-spacing: 0px; border-collapse: separate;">
					  						<thead>
					    						<tr>
					      							<th><?php echo translate('state'); ?></th>
													<th><?php echo translate('issues'); ?></th>
													<th><?php echo translate('percentage'); ?></th>
					    						</tr>
					  						</thead>
											<tbody>
												<?php if( !empty( $this->issueStates ) ): ?>
													<?php foreach( $this->issueStates AS $key => $value ): ?>
														<tr>
															<td style="padding-top: 10px;  vertical-align: top; padding-right: 10px;">
																<?php echo $value['name']; ?>		
															</td>
															<td style="padding-top: 10px;  vertical-align: top; padding-right: 10px;">
																<?php echo $value['count']; ?>		
															</td>
															<td style="padding-top: 10px; vertical-align: top;">
																<div class="progress">
																   <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $value['percentage']; ?>%;">
																   		<span><?php echo $value['percentage']; ?>%</span>
																   </div>
																</div>																
															</td>																														
														</tr>													
													<?php endforeach; ?>
												<?php else: ?>
													<tr>
														<td colspan="3" style="padding-top: 10px; padding-right: 10px;">
															<?php echo translate('no_issues'); ?>		
														</td>
													</tr>												
												<?php endif; ?>											
											</tbody>
										</table>
									</div>		
								</div>											            	
			            	</div>
			          	</div>
			        </div>
			
			        <div class="clearfix"></div>			
			 	</div>    	
	    	</div>
	    </div>
	    <!-- END:	Main Container -->
	    
	    
		<div class="footer">
			<div class="container-fluid">
		    	<div class="row">
		        	<div class="col-lg-12">		
		            	<ul class="list-unstyled">
		              		<li class="pull-right">
		              			<a href="#top" class="backToTop noBlockUI">
		              				<i class="fa fa-chevron-up"></i>
		              			</a>&nbsp;
								<a href="#top" class="backToTop noBlockUI">	              	
									<?php echo translate('to_top'); ?>
		              			</a>
		              		</li>
		              		<li>
		              			<i class="fa fa-rss-square"></i>&nbsp;<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/rss">RSS</a>
		              		</li>
		            	</ul>
		            	<p>&copy; <?php echo translate('copyright'); ?> <?php echo date('Y'); ?> <?php echo SITE_NAME; ?>. <?php echo translate('all_rights_reserved'); ?>.</p>		
		          	</div>
		        </div>
      		</div>
    	</div>
    	    
		<script type="text/javascript">
		    $(document).ready(function() {	
				// Bootstrap Switch
		    	$('.bootstrap-switch').bootstrapSwitch({
			    	'size': 'mini',
			    	'onText': 'Inverse',
			    	'offText': 'Normal',
			    	'onSwitchChange': function(event, state) {
						if( state ) {
							$.cookie('navbar-inverse', 1, { 
								expires: 7300, 
								path: '/',
								onSet: function( value ) {
									$.blockUI();
									window.location.reload();
								}	 
							});
							$('div.navbar').addClass('navbar-inverse');
						} else {
							$('div.navbar').removeClass('navbar-inverse');
							$.removeCookie('navbar-inverse', { 
								path: '/',
								onRemove: function( value ) {
									$.blockUI();
									window.location.reload();
								}
							});
						}	
					 },
					 'onInit': function( event, state ) {
						$('#dropdownThemes').css({
							 'width': ( $('#dropdownThemes').width() + $('#navbarInverse').width() ) + 'px' 
						});

						if( $.cookie('navbar-inverse') == 1 ) {
							$('div.navbar').addClass('navbar-inverse');
						} else {
							$('div.navbar').removeClass('navbar-inverse');
						}						 
					 }		 
			    });
		    			    				    							    		    		   			     			   
				$.imgpreload([
					DEFAULT_PRELOADER_IMAGE, 
					BASEURL + '/images/preloader/168.gif',
					BASEURL + '/images/preloader/small-black.png',
					BASEURL + '/images/preloader/168-black-128x128.png'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});	

				// JSViews
				$.templates({
					templateIssues: '#templateIssues',
					templateActivity: '#templateActivity'
				});

				$('[data-toggle="tab"]').click(function(event) {
				  	$.blockUI({
						message: null
					});
					
				  	setTimeout(function() {
				  	    // animate
				  	    $('.tab-content').hide();
					  	$('.tab-content').fadeIn('slow');
					  	
					  	// unblock					  	
				  		$.unblockUI();
				  	}, 'slow');	
				});

			  	$('[data-toggle="tabAjax"]').click(function(event) {
			  	    var ME = $(this);
			  	    
			  	    // blockUI
				  	$.blockUI({
						message: null
					});
	
				    // activated tab
			  	    var currentTab = event.target 
	
			  	    // part
			  	    var part = ME.data('part');
	
			  	    if( typeof part === 'undefined' ) {
			  	    	return false;
				  	}    
	
			  	    // get the target element
			  	    var targetId = $(currentTab).attr('href').substr(1);

					switch( part ) {
						case 'issues':
							var targetElement = $('#recentIssueList');
							break;
							 
						default:
						  	var targetElement = $('#' + targetId);		
					}
	
					$.ajax({
						type: 'POST',
						url: BASEURL + '/projects/ajax',
						data: { 
							method: 'projectInfo',
							part: part,
							id: <?php echo $this->project['id']; ?>
						},
						complete: function( jqXHR, textStatus ) {
							// ..
						},
						success: function( response, textStatus, jqXHRresponse ) {
							if( response.status == 'OK' ) {
								var data = response.data;
	
								if( data.length > 0 ) {
									// iterate
									$.each(data, function( index, value ) {
										data[index]['date_long']			= date( 'l, F m, Y / h:i:s A e', value.date_created );
										data[index]['date_updated_long']	= ( parseInt( value.date_updated ) > 0 ) ? date( 'l, F m, Y / h:i:s A e', value.date_updated ) : '&mdash;';
										data[index]['priority_name'] 		= translate( value.priority_name );
										data[index]['status_name'] 			= translate( value.status_name );
										data[index]['project_key']			= '<?php echo $this->project['key']; ?>';

										switch( strtolower( value.status_name ) ) {
											case 'assigned':
												data[index]['labelClass'] = 'info';
												break;
											
											case 'confirmed':
												data[index]['labelClass'] = 'primary';
												break;
												
											case 'fixed':												
												data[index]['labelClass'] = 'success';
												break;

											case 'unconfirmed':
												data[index]['labelClass'] = 'warning';
												break;
											
											default:
												data[index]['labelClass'] = 'default';		
										}
									});
									
									// add messages to the DOM
									targetElement.html(
										$.render.templateIssues( response.data )
									);
								} else {
									$('#tblRecentIssues').html( '<div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i> '+ translate('no_data') +'</div>' );
								}					
							} else {
								if( response.status == 'ERROR' ) {
									$('#tblRecentIssues').html( '<div class="alert alert-danger" role="alert"><i class="fa fa-exclamation-triangle"></i> '+ response.error +'</div>' );	
								}	
							}

					  	    // animate
						  	$('.tab-content').hide('slide');
						  	$('.tab-content').show('slide');
							
							// show the tab
							ME.tab('show').promise().done(function( event ) {
							  	// unblock
							  	$.unblockUI();
							});
						},
						error: function(  jqXHR, textStatus, errorThrown ) {
							// ...
						},		
						dataType: 'json'
					});	
			  	    
			  	    return false;
			  	});	

			  	// START:	Highcharts
			  	<?php 
			  		$startTimestamp = $this->startDate; 
			  		// @link	https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC
			  		$startMonth		= ( date( 'm', $startTimestamp ) - 1 );
			  		$startDay		= date( 'd', $startTimestamp );
			  		$startYear		= date( 'Y', $startTimestamp );
			  	?>
			  	
			  	var startMonth	= parseInt(<?php echo $startMonth; ?>); 
			  	var startDay	= parseInt(<?php echo $startDay; ?>);
			  	var startYear	= parseInt(<?php echo $startYear; ?>);
			  	
		        $('#issueChart').highcharts({
		            chart: {
		                type: '<?php echo SITE_ISSUE_CHART_TYPE; ?>',
		                backgroundColor: 'transparent',
		            },
		            title: {
		                text: translate('issues_30_day_summary'),
		                useHTML: true,
		                style: {}
		            },
		            subtitle: {
		            	align: 'center',
		            	floating: false,
		            	style: { 
			            	'color': '#555555' 
				        },
		            	text: '<span class="issuesCreatedCount"><?php echo $this->totalCreated.'</span> '.translate('created', 'strtolower').', <span class="issuesResolvedCount">'.$this->totalResolved.'</span> '.translate('resolved', 'strtolower'); ?>',
		            	useHTML: true
		            },		            
		            legend: {
		                layout: 'vertical',
		                align: 'left',
		                verticalAlign: 'top',
		                x: 150,
		                y: 100,
		                floating: true,
		                borderWidth: 1,
		                backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
		            },
		            colors: ['#de1721', '#45b63f'],
		            xAxis: {
		                type: 'datetime',
		                // 7 days
		                minRange: 7 * 24 * 3600000,
		                labels: {
		                    format: '{value: <?php echo SITE_ISSUE_CHART_XAXIS_DATE_FORMAT; ?>}'
		                }
		            },		            			            	            
		            yAxis: {
		                title: {
		                    text: null
		                }
		            },
		            tooltip: {
			            shared: true,
			            xDateFormat: '<?php echo SITE_ISSUE_CHART_TOOLTIP_DATE_FORMAT; ?>'
		            },
		            credits: {
		                enabled: false
		            },
		            plotOptions: {
		                areaspline: {
		                    fillOpacity: 0.5
		                }
		            },
		            series: [{
		                name: translate('created'),
		                // 24 hours
		                pointInterval: 24 * 3600 * 1000,
		                pointStart: Date.UTC(<?php echo date( "$startYear, $startMonth, $startDay", strtotime( $this->startDate ) ); ?>),
		                data: [
				        <?php if( !empty( $this->created ) ): ?>
				        	<?php foreach( $this->created AS $key => $value ): ?>
				        		<?php echo '['.$value.'],'; ?>
				        	<?php endforeach; ?>
				        <?php endif; ?>
				        ]
		            }, {
		                name: translate('resolved'),
			            // 24 hours
		                pointInterval: 24 * 3600 * 1000,
		                pointStart: Date.UTC(<?php echo date( "$startYear, $startMonth, $startDay", strtotime( $this->startDate ) ); ?>),
		                data: [
				        <?php if( !empty( $this->resolved ) ): ?>
			        		<?php foreach( $this->resolved AS $key => $value ): ?>
		        				<?php echo '['.$value.'],'; ?>
		        			<?php endforeach; ?>
			        	<?php endif; ?>
				        ]
		            }]
		        });	  	

		        // workaround for Highcharts title
		        $('.highcharts-title').html( translate('issues_30day_summary') );
			  	// END:		Highcharts	

		        // START:	get location hash
		        if( window.location.hash ) {
		       		switch( window.location.hash ) {
		       			case '#issues':
			       			$('#triggerIssues').trigger('click');
			       			break;

		       			case '#summary':
			       			$('#triggerSummary').trigger('click');
			       			break;	
		       	 	}
		        }
		        // END:		get location hash

		        // START:	Activity Stream
		        <?php if( has_permission( 'project_can_view_activity_stream' ) ): ?>
			        <?php if( !empty( $this->activity ) ): ?>
			        var activityStream = <?php echo json_encode( $this->activity ); ?>;
	
					$.each( activityStream, function( index, value ) {
						activityStream[index]['project_key']	= '<?php echo $this->project['key']; ?>';
						activityStream[index]['date_long']		= date( 'l, F m, Y / h:i:s A e', value.date ); 
					});
		        
					$('#activityStream').html(
						$.render.templateActivity( activityStream )
					).promise().done(function( event ) {
						$('.activityText').each(function( index, value ) {
							// replace line breaks with br tags
							$(this).replaceText( /\\n/gi, '<br>' );
						});
					});
			        <?php endif; ?>
			    <?php endif; ?>
		        // END:		Activity Stream	

				$('body').imagesLoaded( function() {
					$.unblockUI();
				});															    
		    });		
		    // END:	document.ready    		    				    
		</script>	
		
		<style type="text/css">
			.tabs-left {
  				border-right: 0;
			}
			
			.tabs-left > li.active > a, 
			.tabs-left > li.active > a:focus, 
			.tabs-left > li.active > a:hover {
  				border-bottom: 0;
				font-weight: bold !important;
				border: 1px #000000 solid;
			}
			
			/*.progress {
			    position: relative;
			}
			
			.progress span {
			    position: absolute;
			    display: block;
			    width: 100%;
			 } */			
		</style>
				
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootstrap.min.js"></script>
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootswatch.js"></script>		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jstorage.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/imagesloaded.pkgd.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.defaults.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observor.js?<?php echo rand(); ?>"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/custom.js?<?php echo rand(); ?>"></script>				
				
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootstrap-switch/bootstrap-switch.min.js"></script>			
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>	 
		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/moment/moment.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/livestamp.min.js"></script>
		
		<!-- Highcharts -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/highcharts/highcharts.js"></script>
		
		<!-- replaceText -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.ba-replacetext.min.js"></script>
		
		<!-- SmartMenus -->
		<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/smartmenus/jquery.smartmenus.bootstrap.css" rel="stylesheet">
		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>
		
		<!-- Q -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/q.min.js"></script>
				
		<!-- JsViews -->
		<script id="templateIssues" type="text/x-jsrender">
			<tr>
				<td style="padding-top: 10px; padding-right: 10px;">
					<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/issue/{{>project_key}}-{{>project_issue_id}}">{{>title}}</a>
				</td>
				<td {{if status_name}} alt="{{>status_name}}" title="{{>status_name}}" {{/if}} style="padding-top: 10px; padding-right: 10px;">
					{{if status_name}}<span class="label label-{{>labelClass}}">{{>status_name}}</span>{{else}}&mdash;{{/if}}
				</td>
				<td style="padding-top: 10px; padding-right: 10px;">
					{{>priority_name}}
				</td>
				<td alt="{{>date_long}}" title="{{>date_long}}" style="padding-top: 10px; padding-right: 10px;">
					<span data-livestamp="{{>date_created}}"><?php echo SITE_LOADING_PLACEHOLDER_SMALL; ?></span>
				</td>
				<td {{if date_updated}} alt="{{>date_updated_long}}" title="{{>date_updated_long}}" data-livestamp="{{>date_updated}}" {{/if}} style="padding-top: 10px; padding-right: 10px;">
					{{if date_updated}}
						<?php echo SITE_LOADING_PLACEHOLDER_SMALL; ?>
					{{else}}
						&mdash;
					{{/if}}
				</td>
			</tr>		
		</script>
		
		<script id="templateActivity" type="text/x-jsrender">
			<table id="tblActivity" style="width: 100%; margin-bottom: 10px;">
				<tr>
					<td>
						<a href="<?php echo PROTOCOL_RELATIVE_URL.'/profile/{{>author.url_slug}}'; ?>">{{:author.display_name}}</a> <?php echo translate('commented_on'); ?> <a href="<?php echo PROTOCOL_RELATIVE_URL.'/issue/{{>project_key}}-{{>issue.project_issue_id}}#comment-{{>id}}'; ?>">{{>issue.title}}</a>
					</td>
					<td alt="{{>date_long}}" title="{{>date_long}}" style="align: right; text-align: right;" data-livestamp="{{>date}}">
						<?php echo SITE_LOADING_PLACEHOLDER_SMALL; ?>	
					</td>
				</tr>
				<tr>
					<td colspan="2" style="padding-top: 10px;">
						<div class="activityText alert alert-info" role="alert">
						{{:comment}}
						</div>
					</td>
				</tr>
			</table>		
		</script> 		   
	</body>	
</html>