<!DOCTYPE html>
<html>
	<head>
	    <title><?php echo translate('projects'); ?> &mdash; <?php echo SITE_NAME; ?></title>
	    <meta charset="UTF-8" />
	    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
	    <meta name="apple-mobile-web-app-capable" content="yes" />	    
	    	    
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootswatch.min.css">
	    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/html5shiv.js"></script>
	      <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/respond.min.js"></script>
		<![endif]-->	      	    
	    
	 	<?php
			if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ) {
	 			$currentTheme = ( strlen( @$_COOKIE['theme'] ) ) ? $_COOKIE['theme'] : SITE_DEFAULT_TEMPLATE;

	 			if( strlen( @$_COOKIE['themename'] ) ) {
	 				$themeDisplayName = $_COOKIE['themename'];
	 			}
	 			
			} else {
	 			$currentTheme = SITE_DEFAULT_TEMPLATE;
	 			setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
			}  
		?> 
		
		<?php $siteThemes		= $GLOBALS['SITE_THEMES']; ?>
		<?php $bootstrapThemes	= $GLOBALS['BOOTSTRAP_THEMES']; ?>    	 
				
		<?php if( !empty( $siteThemes ) ): ?>
			
			<?php 		
				if( $currentTheme != SITE_DEFAULT_TEMPLATE ) {
					if( !array_key_exists( $currentTheme, $siteThemes ) ) {
						$currentTheme = SITE_DEFAULT_TEMPLATE;
						setcookie( 'theme', SITE_DEFAULT_TEMPLATE, time() + SITE_COOKIE_TIMEOUT, SITE_COOKIE_PATH );
						
						if( isset( $themeDisplayName ) ) {
							unset( $themeDisplayName );
							setcookie( 'themename', '', time() - 3600, SITE_COOKIE_PATH );
						}
					}
				}
			?>
						
			<script type="text/javascript">	
				var BOOTSTRAP_THEMES	= new Array();	
				var SITE_THEMES			= new Array();
				
				<?php foreach( $siteThemes AS $key => $value ): ?>
					SITE_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';	
				<?php endforeach; ?>

				<?php foreach( $bootstrapThemes AS $key => $value ): ?>
					BOOTSTRAP_THEMES['<?php echo $key; ?>'] = '<?php echo $value; ?>';
				<?php endforeach; ?>				
			</script>
			<?php else: ?>
			<script type="text/javascript">		
				var BOOTSTRAP_THEMES	= new Array();
				var SITE_THEMES			= new Array();
			</script>			
		<?php endif; ?>
		
	    <?php if( !empty( $_SESSION['site']['phrases'] ) ): ?>    
	    	<script type="text/javascript">
	    		var SITE_PHRASES = new Array();
				<?php foreach( $_SESSION['site']['phrases'] AS $key => $value ): ?>
					SITE_PHRASES['<?php echo $key; ?>'] = '<?php echo addslashes( str_replace( "\r\n", '<br>', $value ) ); ?>';
				<?php endforeach; ?>
	    	</script>
	    <?php endif; ?>	
	    
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/phpjs.js?<?php echo rand(); ?>"></script>	    		   
	    
		<script type="text/javascript">
			date_default_timezone_set('UTC');
			
			var BASEURL					= '<?php echo PROTOCOL_RELATIVE_URL; ?>';
			var DEFAULT_PRELOADER_IMAGE	= '<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>';
			var CURRENT_THEME 			= '<?php echo $currentTheme; ?>';
			var CURRENT_USERNAME		= '<?php echo $_SESSION['user']['username']; ?>';
			var SITE_NAME				= '<?php echo SITE_NAME; ?>';		
			var CURRENT_USER			= new Array();
			var UUID					= uuid();		
			var USE_BLOCKUI				= <?php echo (int)SITE_USE_BLOCKUI; ?>;
			var IS_MOBILE				= <?php echo (int)IS_MOBILE; ?>;	
					
			<?php foreach( $_SESSION['user'] AS $key => $value ): ?>
				CURRENT_USER['<?php echo $key; ?>'] = '<?php echo base64_encode( $value ); ?>';
			<?php endforeach; ?>
		</script>     
	
	    <meta name="robots" content="noimageindex" />
	    <link rel="Shortcut Icon" type="image/x-icon" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/favicon.ico" />
	        
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-1.8.3.min.js"></script>	
		
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/custom.css?<?php echo rand(); ?>" type="text/css" />				
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/font-awesome.min.css">
		
		<!-- jQuery UI -->
		<link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/jquery-ui/themes/base/jquery-ui.css">
			    
	    <link id="bootstrapCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/bootstrap.min.css" rel="stylesheet"  media="screen">

		<?php if( $currentTheme != 'bootstrap-with-theme' ): ?>
	    	<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/<?php echo $currentTheme; ?>/bootstrap.min.css" rel="stylesheet">
	    <?php else: ?>
			<link id="themeCSS" media="screen" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/themes/bootstrap/bootstrap.min.css" rel="stylesheet">    
	    <?php endif; ?>										     
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/homepage.css" type="text/css" />	
	    
	    <!-- Sticky Footer -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/sticky-footer-navbar.css" type="text/css" />	
	    
	    <!-- Desktop Sidebar Left -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/desktop-sidebar-left.css" type="text/css" />		
	    
	    <!-- Bootstrap Switch -->
	    <link rel="stylesheet" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/bootstrap/extensions/bootstrap-switch/bootstrap-switch.min.css" type="text/css" />									     
	</head>

	<body>
		<!-- START:		blockUI -->
		<?php if( (int)SITE_USE_BLOCKUI == 1 AND (int)IS_MOBILE != 1 ): ?>
			<div style="display: block" class="blockUI"></div>
			<div style="display: block; z-index: 1000; border: medium none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(0, 0, 0); opacity: 0.6; cursor: wait; position: fixed;" class="blockUI blockOverlay"></div>
			<div style="display: block; z-index: 1011; position: fixed; padding: 0px; margin: 0px; width: 30%; top: 40%; left: 35%; text-align: center; cursor: wait;" class="blockUI blockMsg blockPage"><img src="<?php echo SITE_DEFAULT_PRELOADER_IMAGE_PATH; ?>"></div>
		<?php endif; ?>		
		<!-- END:		blockUI -->	
		<div id="fb-root"></div>
	    <script type="text/javascript">
	      window.fbAsyncInit = function() {
	        FB.init({
	          appId      : '<?php echo SITE_FACEBOOK_APP_ID; ?>',
	          xfbml      : true,
	          version    : 'v2.0'
	        });
	      };
	      (function(d, s, id){
	         var js, fjs = d.getElementsByTagName(s)[0];
	         if (d.getElementById(id)) {return;}
	         js = d.createElement(s); js.id = id;
	         js.src = "//connect.facebook.net/en_US/sdk.js";
	         fjs.parentNode.insertBefore(js, fjs);
	       }(document, 'script', 'facebook-jssdk'));
	    </script>		
		
	    <div class="navbar <?php if( @$_COOKIE['navbar-inverse'] == 1 ): ?> navbar-inverse <?php else: ?> navbar-default <?php endif; ?> navbar-fixed-top">
			<div class="container-fluid">
	        	<div class="navbar-header">
					<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>" class="blockUI-trigger navbar-brand" alt="<?php echo SITE_NAME; ?>" title="<?php echo SITE_NAME; ?>"><i class="fa fa-life-ring"></i></a>
	          		<button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	            		<span class="icon-bar"></span>
	          		</button>
	        	</div>
	        	<div class="navbar-collapse collapse" id="navbar-main">
	          		<ul class="nav navbar-nav">
	          			<!-- START:	Dashboards -->
	          			<li class="dropdown">
	          				<a id="dropdownDashboards" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('dashboards');?></a>
			              	<ul aria-labelledby="dropdownDashboards" class="dropdown-menu">
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>">
										<?php echo translate( 'system_dashboard' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Dashboards -->

	          			<!-- START:	Projects -->
	          			<li class="dropdown">
	          				<a id="dropdownProjects" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('projects');?></a>
			              	<ul aria-labelledby="dropdownProjects" class="dropdown-menu">
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/projects">
										<?php echo translate( 'view_all_projects' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Projects -->

	          			<!-- START:	Issues -->
	          			<li class="dropdown">
	          				<a id="dropdownIssues" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('issues');?></a>
			              	<ul aria-labelledby="dropdownIssue" class="dropdown-menu">
								<?php if( has_permission( 'can_create_issues' ) ): ?>
								<li>
									<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/issue/create">
										<?php echo translate( 'create_issue' ); ?>
									</a>
			              		</li>			              	
			              		<?php endif; ?>			              	
								<li>
									<a href="#">
										<?php echo translate( 'search_issues' ); ?>
									</a>
			              		</li>
							</ul>	          			
						</li>
	          			<!-- END:	Issues -->
	          		
			            <?php if( (int)SITE_ALLOW_TEMPLATE_CHANGE == 1 ): ?>        
			            <li class="dropdown">
			              <a id="themes" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('themes');?> (<?php echo count( $GLOBALS['SITE_THEMES'] ); ?>)</a>
			              <ul aria-labelledby="themes" class="dropdown-menu" id="dropdownThemes">
							<li>								
								<a id="linkThemeCurrent" href="#" class="changeTheme" data-displayname="" data-name="<?php echo strtolower( $currentTheme ); ?>">
									<?php echo ( isset( $themeDisplayName ) ) ? $themeDisplayName : ucfirst( $currentTheme ); ?>
								</a>
			              	</li>
			              	<li>
			              		<a href="#"><div><input data-size="normal" class="bootstrap-switch" type="checkbox" id="navbarInverse" name="navbarInverse" value="1" <?php if( @$_COOKIE['navbar-inverse'] == 1 ): ?> checked="checked"<?php endif; ?>></div></a>
			              	</li>			              	
			              	<li class="divider"></li>
			              	<?php foreach( $GLOBALS['SITE_THEMES'] AS $key => $value ): ?>
		                		<li <?php if( strtolower( $key ) == strtolower( $currentTheme ) ): ?> class="active" <?php endif; ?>>
		                			<?php if( array_key_exists( $key, $GLOBALS['BOOTSTRAP_THEMES'] ) ): 
		                				$isBootstrap = true;
		                			else:
		                				$isBootstrap = false;
		                			endif; 
		                			?>
		                			<a <?php if( strtolower( $key ) == strtolower( $currentTheme ) ): ?> style="font-weight: bold;" <?php endif; ?> href="#" class="changeTheme <?php echo strtolower( $key ); ?>" data-bootstrap="<?php echo $isBootstrap; ?>" data-displayname="<?php echo $value; ?>" data-name="<?php echo strtolower( $key ); ?>">
		                				<?php echo $value; ?>
									</a>                			
								</li>
			              	<?php endforeach; ?>
			              </ul>
			            </li>
			            <?php endif; ?>
			            			            			            
			            <?php if( (int)SITE_ALLOW_LANGUAGE_CHANGE == 1 ): ?> 
			            	<?php if( !empty( $GLOBALS['SITE_LANGUAGES'] ) ): ?>			            	       
			            		<li class="dropdown">
					              <a id="changeLang" href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo translate('language'); ?></a>
					              <ul aria-labelledby="changeLang" class="dropdown-menu">
									<li>
										<a id="linkLanguageCurrent" href="#" class="changeLang" data-name="<?php echo strtolower( $currentTheme ); ?>">
											<?php $CloneUI_Language = new CloneUI_Language; ?>
											<?php echo $CloneUI_Language->fetchFriendlyNameById( $_SESSION['user']['site_language'] ); ?>
										</a>
					              	</li>
				                		<li class="divider"></li>
						              	<?php foreach( $GLOBALS['SITE_LANGUAGES'] AS $key => $value ): ?>
					                		<li>
					                			<?php if( $value['id'] != $_SESSION['user']['site_language'] ): ?>
						                			<a href="#" class="changeLang" id="changeLang-<?php echo $value['id']; ?>" data-id="<?php echo $value['id']; ?>" data-name="<?php echo $value['iso_3166_1']; ?>">
						                				<?php echo $value['friendly_name']; ?>
													</a>
												<?php else: ?>
													<a class="noBlockUI">
														<?php echo $value['friendly_name']; ?>
													</a>																										
												<?php endif; ?>               			
											</li>              	
						              	<?php endforeach; ?>
			              			</ul>
			            		</li>
			            	<?php endif; ?>			            		
			            <?php endif; ?>			             		             
	          		</ul>

					<!-- START:	Search Form -->
					<form action="<?php echo PROTOCOL_RELATIVE_URL; ?>/search" method="GET" name="frmSiteSearch" id="frmSiteSearch" class="navbar-form navbar-left">
	                	<input name="q" id="frmSearchQuery" type="text" placeholder="<?php echo translate('search'); ?>" class="form-control col-lg-8">
	                </form>
					<!-- END:	Search Form -->
	
	          		<ul class="nav navbar-nav navbar-right">
	            		<li class="dropdown">
	              			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-help"> <i class="fa fa-question-circle"></i></a>
	              			<ul class="dropdown-menu" aria-labelledby="dropdown-help">
		            			<li>
		            				<a id="aboutJordon" href="#"><?php echo translate('about'); ?> Jordon</a>
		            			</li>
	              			</ul>
	            		</li>
	          			<?php if( (int)$_SESSION['user']['logged_in'] == 1 ): ?>
	            		<li class="dropdown">
	              			<a class="dropdown-toggle" data-toggle="dropdown" href="#" id="dropdown-user"><?php if( isset( $_SESSION['user']['external']['network'] ) ):?> <i class="fa fa-<?php echo $_SESSION['user']['external']['network']; ?>"></i> <?php endif;?><?php echo $_SESSION['user']['email']; ?></a>
	              			<ul class="dropdown-menu" aria-labelledby="dropdown-user">
		            			<li>
		            				<a id="linkLogout" href="<?php echo PROTOCOL_RELATIVE_URL; ?>/logout"><?php echo translate('logout'); ?></a>
		            			</li>
	              			</ul>
	            		</li>	
	            		<?php else: ?>       
            			<li>
            				<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/login"><?php echo translate('login'); ?></a>
            			</li>	            		
	            		<?php endif; ?>   		
	          		</ul>
	        	</div>
			</div>
		</div>
	
	
		<!-- START:		Main Container -->
	    <div class="container-fluid">	
	    	<div class="row" style="margin-left: 10px;">
	    		<h1 class="page-header" id="labelProjects"><?php echo translate('all_projects'); ?></h1>
	    	</div>
			<div class="row row-offcanvas row-offcanvas-left">		        
		        <!-- sidebar -->
		        <div role="navigation" id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
		            <ul class="nav projectList">
		            	<?php if( !empty( $this->projectCategory ) ): ?>
		            		<?php foreach( $this->projectCategory AS $key => $value ): ?>
			              		<li data-category="<?php echo $value['id']; ?>" class="triggerProjectList">
			              			<a href="#"><?php echo $value['title']; ?></a>
			              		</li>
			              	<?php endforeach; ?>
		            	<?php endif; ?>
			           	<li data-category="uncategorized" class="triggerProjectList">
			            	<a href="#"><?php echo translate('uncategorized'); ?></a>
			        	</li>		            	
			           	<li data-category="all" class="triggerProjectList active">
			            	<a href="<?php echo PROTOCOL_RELATIVE_URL.'/projects'; ?>"><?php echo translate('all_projects'); ?></a>
			        	</li> 
		            </ul>
		        </div>
		  	
		        <!-- main area -->
		        <div class="col-xs-12 col-sm-9">
					<?php if( !empty( $this->projectCategory ) ): ?>
						<?php foreach( $this->projectCategory AS $key => $value ): ?>
							<div class="projectLegend" id="projects-<?php echo $value['id']; ?>">
							<h3 style="margin-bottom: 10px;"><?php echo $value['title']; ?></h3>
							<?php if( !empty( $this->projects ) ): ?>
								<table class="table table-striped table-hover" style="margin-bottom: 30px;">
									<thead>
								    	<tr>
								      		<th>&nbsp;</th>
								      		<th>Project</th>
								      		<th>Key</th>
								      		<th>Project Lead</th>
											<th>URL</th>
								    	</tr>
								  	</thead>
								  	<tbody>								 							
										<?php foreach( $this->projects AS $projectKey => $projectValue ): ?>
											<?php if( in_array( $value['id'], $projectValue['metadata']['category_id'] ) ): ?>
										    	<tr>
										      		<td><?php echo $projectValue['branding']; ?></td>
										      		<td>
														<a href="<?php echo PROTOCOL_RELATIVE_URL.'/project/'.$projectValue['key']; ?>"><?php echo $projectValue['title']; ?></a>
													</td>
										      		<td>
														<?php echo $projectValue['key']; ?>
													</td>
										      		<td>
										      			<?php echo ( (int)$projectValue['lead'] > 0 ) ? '<a href="'.PROTOCOL_RELATIVE_URL.'/profile/'.$projectValue['metadata']['lead_info']['url_slug'].'" target="_blank">'.$projectValue['metadata']['lead_info']['first_name'].' '.$projectValue['metadata']['lead_info']['last_name'] : '&mdash;' ;?>
										      		</td>
													<td>
														<a href="<?php echo $projectValue['url']; ?>" target="_blank"><?php echo $projectValue['url']; ?></a>
													</td>
										    	</tr>
										    <?php endif; ?>
										<?php endforeach; ?>
									</tbody>
								</table>
							<?php endif; ?>	
							</div>						
						<?php endforeach; ?>						 
					<?php endif; ?>
					
					<!-- START:	Uncategorized -->
					<?php $i = 0; $x = 0; $count = count( $this->projects ); foreach( $this->projects AS $key => $value ): ?>
						<?php $i++; ?>
						<?php if( empty( $value['metadata']['category'] ) ): ?>
						<?php $x++; ?>
						<?php if( $x == 1 ): ?>
						<div class="projectLegend" id="projects-uncategorized">
						<h3 style="margin-bottom: 10px;"><?php echo translate('uncategorized'); ?></h3>
							<table class="table table-striped table-hover ">
								<thead>
							    	<tr>
							      		<th>&nbsp;</th>
							      		<th>Project</th>
							      		<th>Key</th>
							      		<th>Project Lead</th>
										<th>URL</th>
							    	</tr>
							  	</thead>
							  	<tbody>
						<?php endif; ?>								 							
							    	<tr>
							      		<td><?php echo $value['branding']; ?></td>
							      		<td>
											<a href="<?php echo PROTOCOL_RELATIVE_URL.'/project/'.$value['key']; ?>"><?php echo $value['title']; ?></a>
										</td>
							      		<td>
											<?php echo $value['key']; ?>
										</td>
							      		<td>
							      			<?php echo ( (int)$value['lead'] > 0 ) ? '<a href="'.PROTOCOL_RELATIVE_URL.'/profile/'.$value['metadata']['lead_info']['url_slug'].'" target="_blank">'.$value['metadata']['lead_info']['first_name'].' '.$value['metadata']['lead_info']['last_name'] : '&mdash;' ;?>
							      		</td>
										<td>
											<a href="<?php echo $value['url']; ?>" target="_blank"><?php echo $value['url']; ?></a>
										</td>
							    	</tr>
						<?php endif; ?>
						<?php if ( $i == $count ): ?>
								</tbody>
							</table>
						</div>	
						<?php endif; ?>						
					<?php endforeach; ?>
					<!-- END:	Uncategorized -->
		          
		        </div><!-- /.col-xs-12 main -->
			</div>
	    </div>
	    <!-- END:	Main Container -->
	    
	    
		<div class="footer">
			<div class="container-fluid">
		    	<div class="row">
		        	<div class="col-lg-12">		
		            	<ul class="list-unstyled">
		              		<li class="pull-right">
		              			<a href="#top" class="backToTop noBlockUI">
		              				<i class="fa fa-chevron-up"></i>
		              			</a>&nbsp;
								<a href="#top" class="backToTop noBlockUI">	              	
									<?php echo translate('to_top'); ?>
		              			</a>
		              		</li>
		              		<li>
		              			<i class="fa fa-rss-square"></i>&nbsp;<a href="<?php echo PROTOCOL_RELATIVE_URL; ?>/rss">RSS</a>
		              		</li>
		            	</ul>
		            	<p>&copy; <?php echo translate('copyright'); ?> <?php echo date('Y'); ?> <?php echo SITE_NAME; ?>. <?php echo translate('all_rights_reserved'); ?>.</p>		
		          	</div>
		        </div>
      		</div>
    	</div>
    	    
		<script type="text/javascript">
		    $(document).ready(function() {	
				// Bootstrap Switch
		    	$('.bootstrap-switch').bootstrapSwitch({
			    	'size': 'mini',
			    	'onText': 'Inverse',
			    	'offText': 'Normal',
			    	'onSwitchChange': function(event, state) {
						if( state ) {
							$.cookie('navbar-inverse', 1, { 
								expires: 7300, 
								path: '/',
								onSet: function( value ) {
									$.blockUI();
									window.location.reload();
								}	 
							});
							$('div.navbar').addClass('navbar-inverse');
						} else {
							$('div.navbar').removeClass('navbar-inverse');
							$.removeCookie('navbar-inverse', { 
								path: '/',
								onRemove: function( value ) {
									$.blockUI();
									window.location.reload();
								}
							});
						}	
					 },
					 'onInit': function( event, state ) {
						$('#dropdownThemes').css({
							 'width': ( $('#dropdownThemes').width() + $('#navbarInverse').width() ) + 'px' 
						});

						if( $.cookie('navbar-inverse') == 1 ) {
							$('div.navbar').addClass('navbar-inverse');
						} else {
							$('div.navbar').removeClass('navbar-inverse');
						}						 
					 }		 
			    });
		    			    				    							    		    		   			     			   
				$.imgpreload([
					DEFAULT_PRELOADER_IMAGE, 
					BASEURL + '/images/preloader/168.gif'
					], {
				    each: function() {
				        // this = dom image object
				        // check for success with: $(this).data('loaded')
				        // callback executes on every image load
				    },
				    all: function() {
				        // this = array of dom image objects
				        // check for success with: $(this[i]).data('loaded')
				        // callback executes when all images are loaded				    		    			    			        
				    }
				});						
						    
				$('body').imagesLoaded( function() {
					$.unblockUI();
				});																    
		    });		    				    		    		    				    
		</script>	
		
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootstrap.min.js"></script>
	    <script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/bootswatch.js"></script>		
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.cookie.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery-ui-1.9.2.custom.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/projects.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.imgpreload.min.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/imagesloaded.pkgd.min.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.js"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.blockUI.defaults.js"></script>	
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/jquery.observor.js?<?php echo rand(); ?>"></script>
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/custom.js?<?php echo rand(); ?>"></script>				
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootstrap-switch/bootstrap-switch.min.js"></script>			
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/bootstrap/extensions/bootbox/bootbox.js"></script>	    
		
		<!-- SmartMenus -->
		<link href="<?php echo PROTOCOL_RELATIVE_URL; ?>/css/smartmenus/jquery.smartmenus.bootstrap.css" rel="stylesheet">
		<!-- SmartMenus jQuery plugin -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.js"></script>
		<!-- SmartMenus jQuery Bootstrap Addon -->
		<script type="text/javascript" src="<?php echo PROTOCOL_RELATIVE_URL; ?>/js/smartmenus/jquery.smartmenus.bootstrap.js"></script>
	</body>	
</html>